Repository bgonzalezcbcv/cb-web, pull requests merged in 2022-10, with the labels that each got.

#30 FE-13: Errors showing on student creation dialog.
  src/components/ErrorList/ErrorList.scss
  src/components/ErrorList/ErrorList.tsx
  src/components/ErrorList/testing/ErrorList.spec.tsx
  src/components/ErrorList/testing/__snapshots__/ErrorList.spec.tsx.snap
  src/components/ErrorList/testing/testingData.json
  src/components/ErrorList/testing/testingDataSchema.json
  src/core/AJVHelper.ts
  src/core/CoreHelper.ts
  src/pages/student/StudentErrors.ts
  src/pages/student/components/AdministrativeInfo/DiscountsSection/DiscountsSection.tsx
  src/pages/student/components/AdministrativeInfo/DiscountsSection/ui.json
  src/pages/student/components/AdministrativeInfo/PaymentMethodsSection/ui.json
  src/pages/student/components/CreateStudentDialog/CreateStudentDialog.tsx
  src/pages/student/components/CreateStudentDialog/testing/CreateStudentDialog.test.tsx
  src/pages/student/components/CreateStudentDialog/testing/__snapshots__/CreateStudentDialog.test.tsx.snap
  src/pages/student/components/FamilyForm/FamilyForm.tsx
  src/pages/student/components/StudentInfo/StudentInfo.tsx
  src/pages/student/schema.json
Labels: enhancement

#36 required-error-list-fix
  src/core/AJVHelper.ts
Labels: bug

#16 FE-9: add ThemeProvider and theme
  package-lock.json
  package.json
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  public/manifest.json
  src/App.css
  src/App.tsx
  src/assets/logo_horizontal.svg
  src/assets/logo_vertical.svg
  src/components/Navbar/Navbar.tsx
  src/components/Sidebar/Sidebar.scss
  src/components/Sidebar/Sidebar.tsx
  src/components/modal/Modal.tsx
  src/core/theme.ts
  src/pages/student/Student.tsx
  src/pages/student/components/AdministrativeInfo/AdministrativeInfo.scss
  src/pages/student/components/AdministrativeInfo/DiscountsSection/DiscountsSection.scss
  src/pages/student/components/AdministrativeInfo/DiscountsSection/DiscountsSection.tsx
  src/pages/student/components/AdministrativeInfo/PaymentMethodsSection/PaymentMethodSection.tsx
  src/pages/student/components/AdministrativeInfo/historyTables/DiscountHistory.tsx
  src/pages/student/components/AdministrativeInfo/historyTables/PaymentMethodHistory.tsx
  src/pages/student/components/CreateStudentDialog/CreateStudentDialog.tsx
  src/pages/student/components/CreateStudentDialog/testing/__snapshots__/CreateStudentDialog.test.tsx.snap
  src/pages/student/components/StudentPageHeader/Student.scss
  src/pages/student/components/StudentPageHeader/StudentPageHeader.tsx
  src/pages/student/components/StudentPageTabs/StudentPageTabs.tsx
  src/pages/student/components/index.ts
  tsconfig.json
Labels: enhancement

#37 BUG-10: Adds debounce to setStudent callback to panels.
  src/pages/student/Student.tsx
Labels: bug

#43 FE-18: Errores inputs en blanco y requeridos
  src/core/CoreHelper.ts
  src/core/Parsers.ts
  src/pages/student/Student.tsx
  src/pages/student/components/AdministrativeInfo/AdministrativeInfo.tsx
  src/pages/student/components/FamilyForm/FamilyForm.tsx
  src/pages/student/components/StudentInfo/StudentInfo.tsx
  src/pages/student/components/StudentInfo/ui.json
  src/pages/student/schema.json
Labels: enhancement

#41 FE-14: Añadidos modos de edicion y de vista en pagina de Student.
  src/App.tsx
  src/core/AJVHelper.ts
  src/core/ApiStore.ts
  src/core/interfaces.ts
  src/pages/student/DefaultStudent.tsx
  src/pages/student/Student.test.tsx
  src/pages/student/Student.tsx
  src/pages/student/__snapshots__/Student.test.tsx.snap
  src/pages/student/components/CreateStudentDialog/CreateStudentDialog.tsx
  src/pages/student/components/CreateStudentDialog/testing/CreateStudentDialog.test.tsx
  src/pages/student/components/CreateStudentDialog/testing/__snapshots__/CreateStudentDialog.test.tsx.snap
  src/pages/student/components/StudentPageHeader/StudentPageHeader.tsx
  src/pages/student/components/StudentPageTabs/StudentPageTabs.tsx
Labels: enhancement

#42 axios-middleware: Adds axios middleware to log out on 403 API request error.
  src/core/ApiStore.ts
Labels: enhancement

#54 FE-21
  package-lock.json
  src/App.tsx
  src/components/Navbar/Navbar.tsx
  src/core/ApiStore.ts
  src/core/CoreHelper.ts
  src/core/DataStore.ts
  src/core/Models.ts
  src/core/interfaces.ts
  src/core/schemas/user_info.json
  src/core/userRoleHelper.ts
  src/pages/createuser/CreateUser.test.tsx
  src/pages/createuser/CreateUser.tsx
  src/pages/createuser/components/CreateUserDialog.tsx
  src/pages/createuser/ui.json
  src/pages/user/CreateUser.test.tsx
  src/pages/user/User.module.scss
  src/pages/user/User.tsx
  src/pages/user/components/Absences/Absences.tsx
  src/pages/user/components/Absences/absences-ui.json
  src/pages/user/components/ComplementaryInfo/ComplementaryInformation.tsx
  src/pages/user/components/ComplementaryInfo/complementary-info-add-item-ui.json
  src/pages/user/components/ComplementaryInfo/complementary-info-ui.json
  src/pages/user/components/CreateUserDialog.tsx
  src/pages/user/components/Documents/Documents.tsx
  src/pages/user/components/Documents/documents-ui.json
  src/pages/user/components/PersonalInfo/PersonalInformation.tsx
  src/pages/user/components/PersonalInfo/personal-info-ui.json
  src/pages/user/components/ProfileCard/ProfileCard.tsx
  src/pages/user/components/ProfileCard/ProfileCardItemGroup.tsx
  src/pages/user/schema.json
  src/pages/user/tests/User.test.tsx
  src/pages/user/tests/__snapshots__/User.test.tsx.snap
Labels: enhancement

#66 BUG-169: Fixes NumberInput not working with null value.
  src/components/NumericInput/NumericInput.tsx
Labels: bug, enhancement
